var creep_templates = {
    rcl_1: {//MAX: 300
        'harvester':[
            /*NONE*/
        ],
        'janitor':[
            /*NONE*/
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[
            /*NONE*/
        ],
        'miner':[
            /*NONE*/
        ],
        'builder':[
            /*NONE*/
        ],
        'transporter':[
            /*NONE*/
        ],
        'starter':[
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[
            /*NONE*/
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    },
    rcl_2: {//MAX: 550
        'harvester':[
            /*NONE*/
        ],
        'janitor':[
            /*NONE*/
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[
            /*NONE*/
        ],
        'miner':[
            /*NONE*/
        ],
        'builder':[
            /*NONE*/
        ],
        'transporter':[
            /*NONE*/
        ],
        'starter':[
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[
            /*NONE*/
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    },
    rcl_3: {//MAX: 800
        'harvester':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'janitor':[//650
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'miner':[//750
            WORK,WORK,WORK,WORK,WORK,
            CARRY,CARRY,
            MOVE,MOVE,MOVE
        ],
        'builder':[//750
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'transporter':[//750
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'starter':[//300
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[//800
            WORK,WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    },
    rcl_4: {//MAX: 1300
        'harvester':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'janitor':[//650
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'miner':[//850
            WORK,WORK,WORK,WORK,WORK,WORK,
            CARRY,CARRY,
            MOVE,MOVE,MOVE
        ],
        'builder':[//1050
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'transporter':[//1200
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'starter':[//300
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[//1300
            WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'upgrade_booster':[//1200
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ]
    },
    rcl_5: {//MAX: 1800
        'harvester':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'janitor':[//650
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'linker':[//150
            CARRY,CARRY,
            MOVE
        ],
        'tower_filler':[//600
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE
        ],
        'miner':[//850
            WORK,WORK,WORK,WORK,WORK,WORK,
            CARRY,CARRY,
            MOVE,MOVE,MOVE
        ],
        'builder':[//1050
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'transporter':[//1200
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'starter':[//300
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[//1300
            WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ],
        'upgrade_booster':[//1200
            WORK,WORK,WORK,
            CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,
            MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
        ]
    },
    rcl_6: {//MAX: 2300
        'harvester':[
            /*NONE*/
        ],
        'janitor':[
            /*NONE*/
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[
            /*NONE*/
        ],
        'miner':[
            /*NONE*/
        ],
        'builder':[
            /*NONE*/
        ],
        'transporter':[
            /*NONE*/
        ],
        'starter':[
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[
            /*NONE*/
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    },
    rcl_7: {//MAX: 5300
        'harvester':[
            /*NONE*/
        ],
        'janitor':[
            /*NONE*/
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[
            /*NONE*/
        ],
        'miner':[
            /*NONE*/
        ],
        'builder':[
            /*NONE*/
        ],
        'transporter':[
            /*NONE*/
        ],
        'starter':[
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[
            /*NONE*/
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    },
    rcl_8: {//MAX: 12300
        'harvester':[
            /*NONE*/
        ],
        'janitor':[
            /*NONE*/
        ],
        'linker':[
            /*NONE*/
        ],
        'tower_filler':[
            /*NONE*/
        ],
        'miner':[
            /*NONE*/
        ],
        'builder':[
            /*NONE*/
        ],
        'transporter':[
            /*NONE*/
        ],
        'starter':[
            WORK,
            CARRY,CARRY,
            MOVE,MOVE
        ],
        'upgrader':[
            /*NONE*/
        ],
        'upgrade_booster':[
            /*NONE*/
        ]
    }
}